channels:
  - conda-forge

dependencies:
    # If available, always prefer the conda version of a package.
    # Installation will be faster and more efficient.
    - python=3.10.6
    - pip=22.2.2
    - keyring=23.9.1 # https://keyring.readthedocs.io/en/latest/
    - rpaframework-recognition=5.0.0 # https://anaconda.org/conda-forge/rpaframework-recognition

    - pip:
        # Framework dependencies
        - playwright==1.25.2 # https://playwright.dev/python/docs/library
        - PyAutoGUI==0.9.53 # https://pyautogui.readthedocs.io/en/latest/
        - rpaframework==16.3.0 # https://rpaframework.org/index.html

        # Process-specific dependencies
        - xhtml2pdf==0.2.8 # https://xhtml2pdf.readthedocs.io/en/latest/

rccPostInstall:
  - playwright install